Minor wording recommendations
actix/actix-website pull request #184
Opened 2020-09-04 06:01 UTC by snoyberg

So far I've only reviewed application and getting-started. If these
kinds of tweaks are desired, I'll continue with further PRs when I have
an opportunity to do so.

2020-09-04 09:01 UTC, robjtede requested changes
Thanks for these text reviews. I'd hold off on any more for a short while because the website will be getting updated with v3 information soon.

2020-09-04 12:10 UTC, snoyberg commented on content/docs/application.md
> +Internally, [`web::Data`][data] uses `Arc`. Thus, in order to avoid creating two `Arc`s, we should create our Data before registering it using [`App::app_data()`][appdata].
I don't think this is the issue. It's not about _nested_ `Arc`s. The issue is that if we create the value inside the closure, it will create a new value each time an `App` is created.

2020-09-04 12:12 UTC, snoyberg commented
Thanks for the review, and thanks for the comment above:

> Thanks for these text reviews. I'd hold off on any more for a short while because the website will be getting updated with v3 information soon.

I included 3/4 suggestions, and left a comment on the last one.

2020-09-04 12:19 UTC, robjtede commented on content/docs/application.md
> +Internally, [`web::Data`][data] uses `Arc`. Thus, in order to avoid creating two `Arc`s, we should create our Data before registering it using [`App::app_data()`][appdata].
Looking at the wider context, nesting should maybe be a separate point. In fact, this whole section needs a rework. We'll leave your change as-is here.

2020-09-04 12:19 UTC, robjtede approved these changes

2020-09-04 12:19 UTC, merged

2020-09-05 17:07 UTC, snoyberg commented
Thank you!