Migrate to docusaurus
actix/actix-website pull request #222
Opened 2021-03-31 15:33 UTC by ibraheemdev

![image](https://user-images.githubusercontent.com/34988408/113170536-a3cc2b80-9214-11eb-9e80-b9a305ecf99c.png)
![image](https://user-images.githubusercontent.com/34988408/113170703-cd855280-9214-11eb-919d-714ce46da75b.png)

- [ ] re-add some files (license, cname)
- [ ] inline code blocks
- [ ] update home page

2021-12-05 23:29 UTC, nikstur commented
Is there (still) interest by the maintainers in migrating to Docusaurus? I don't know in what detail this has been discussed before, but here is my opinion:

Im generally in favour of Docusaurus:

Pros:
- Designed solely for documentation
- Easier to support multiple versions of the website for different releases of actix-web (there is no straightforward way in Hugo)
- Easier to support i18n (less manual work needed than in Hugo)
- Looks prettier (including night mode --- very subjective of course) 
- Benefit from updates through a simple version bump instead of building it by ourselves
- Solves license issue mentioned in the readme of this repo.

Cons:
- Variable substitution in markdown is a bit ugly. The entire line has to be wrapped in an JSX element.  
  
  Example:
  ```jsx
  <>Actix Web currently has a minimum supported Rust version (MSRV) of { rustVersion }</>
  ```
  
  It's even worse in code blocks: The entire block has to be written in JSX and the content has to be escaped to retain line breaks.
  ```jsx
  <RenderCodeBlock className="language-toml">
  {`[dependencies]
  actix-web = "${actixWebVersion}"`}
  </RenderCodeBlock>
  ```
  However right now variables are not used very often: the rust and actix-web versions are mentioned in just two files each. It might be feasible to either hardcode the variables or use the "ugly" JSX syntax 
- Javascript tooling (npm or yarn)
- Yet another tool to learn and support (however its still mostly markdown of course)

If there is interest, I'd volunteer for reviewing the PR in depth (I've looked over it but haven't commented on the issues I found) and helping out with the finishing touches if @ibraheemdev is not available anymore.

2021-12-05 23:52 UTC, robjtede commented
From the maintainers, there is still interest in migrating. The only thing holding this PR back is a homepage refresh.

2021-12-06 02:16 UTC, ibraheemdev commented
> I'd volunteer for reviewing the PR in depth (I've looked over it but haven't commented on the issues I found) and helping out with the finishing touches

That would be great :)

> The only thing holding this PR back is a homepage refresh.

I think to avoid the list of conflicts growing even more, we can use the current home page and refresh it later.

2021-12-06 15:57 UTC, nikstur requested changes
LGTM, however there are a few (larger) issues we should fix before merging:

- [ ] Fix conflicts 
- [ ] Update `docusaurus-plugin-sass` and add `sass` dev dependency
<s>- [ ] Factor out changes to examples (actual content) into a separate PR</s>

A few things we can and should do after merging in separate PRs:

- Remove superfluous information from yaml metadata header in all markdown files
- Fix headings: Hugo renders them correctly (h1 turns into h2), however, docusaurus doesn't, so they all need to be h2 headings

2021-12-06 15:57 UTC, nikstur commented on examples/flexible-responders/src/main.rs
> +// </flexible-responders>
Same here as in examples/easy-form-handling/src/main.rs

2021-12-06 15:57 UTC, nikstur commented on examples/powerful-extractors/src/main.rs
> +// <powerful-extractors>
Same as in examples/easy-form-handling/src/main.rs

2021-12-06 15:57 UTC, nikstur commented on examples/request-routing/src/main.rs
> -// <request-routing>
Same as in examples/easy-form-handling/src/main.rs

2021-12-06 15:57 UTC, nikstur commented on package.json
> +    "docusaurus-plugin-sass": "^0.1.12",
We should probably update all dependencies, but we definiteley need to update `docusaurus-plugin-sass` and add `sass` as a dev dependency.
The current version pulls in a node-sass version that requires Python2 (and thus will fail on many modern systems).

2021-12-06 15:57 UTC, nikstur commented on sidebars.js
> +            'handlers',
These are the exchanged in the current docs. The handlers page comes first

2021-12-06 15:57 UTC, nikstur commented on src/pages/index.js
> +import TabItem from "@theme/TabItem";
These are unused and can be removed.

2021-12-06 15:57 UTC, nikstur commented on .gitignore
> -Cargo.lock
Is this what we want or is it accidental? If it was accidental, the committed Cargo.lock file should also be removed.

2022-03-17 07:32 UTC, Woile commented
@ibraheemdev I think I can finish this PR, do you mind if I continue it?

2022-03-17 15:48 UTC, ibraheemdev commented
Sure! I don't think I have the energy to fix all the merge conflicts 😅

2022-03-17 15:50 UTC, robjtede commented
Surely easier to re-apply the changes from this diff manually in its own fork. There's been a lot of changes and I wouldn't trust a merge conflict solve at this point.

2022-03-18 14:59 UTC, Woile commented on docs/getting-started.md
> +<>Actix Web currently has a minimum supported Rust version (MSRV) of { rustVersion }. Running <code>rustup update</code> will ensure you have the latest and greatest Rust version available. As such,
For #266 using `p` which makes it same as a markdown text.

2022-03-18 15:12 UTC, Woile commented on docs/getting-started.md
>  ```
done 4 #266

2022-03-18 15:16 UTC, Woile commented on docs/server.md
>  ```
Done #266

2022-03-18 15:16 UTC, Woile commented on docs/websockets.md
> +import CodeBlock from "../src/components/code_block.js";
Done #266

2022-03-18 15:39 UTC, Woile commented on docs/whatis.md
> +<>Most importantly: <code>actix-web</code> runs on Rust { rustVersion } or later and it works with stable releases.</>
Done https://github.com/actix/actix-website/pull/266

2022-03-18 15:40 UTC, Woile commented
I think I've covered most of the comments in the PR #266 can u take a look @nikstur ? Thanks

2022-03-18 15:53 UTC, nikstur commented
Great, thank you for the work! I'll take a look.

2022-03-18 15:55 UTC, robjtede commented
superseded by #266

2022-03-18 15:55 UTC, closed without merging